# Generated by Django 5.1.3 on 2024-12-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_adminregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminregister_name', models.CharField(max_length=50)),
                ('adminregister_email', models.CharField(max_length=50)),
                ('adminregister_password', models.CharField(max_length=50)),
            ],
        ),
    ]
