# Generated by Django 5.1.3 on 2024-12-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_product',
        ),
    ]
