# Generated by Django 5.1.3 on 2024-12-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=30)),
                ('work_details', models.CharField(max_length=30)),
                ('work_photo', models.FileField(max_length=30, upload_to='')),
            ],
        ),
    ]
