# Generated by Django 5.1.3 on 2024-12-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0002_tbl_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_work',
        ),
    ]
