# Generated by Django 5.1.3 on 2024-12-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0004_tbl_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
    ]
