# Generated by Django 5.1.3 on 2024-12-19 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0005_delete_tbl_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_photo', models.FileField(max_length=30, upload_to='')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Designer.tbl_work')),
            ],
        ),
    ]
