# Generated by Django 5.1.3 on 2024-12-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0007_tbl_designrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_designrequest',
        ),
    ]
