# Generated by Django 5.1.3 on 2024-12-22 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0006_tbl_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_details', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=30)),
                ('product_photo', models.CharField(max_length=30)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop')),
            ],
        ),
    ]
