# Generated by Django 5.1.3 on 2024-12-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_stock',
            name='product',
        ),
        migrations.DeleteModel(
            name='tbl_product',
        ),
        migrations.DeleteModel(
            name='tbl_stock',
        ),
    ]
