# Generated by Django 5.1.3 on 2024-12-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_stock',
        ),
    ]
