# Generated by Django 5.1.4 on 2025-01-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_tbl_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_chat',
        ),
    ]
