# Generated by Django 5.1.7 on 2025-04-07 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_tbl_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_chat',
        ),
    ]
