from django.urls import path
from Admin import views
app_name="Admin"

urlpatterns = [
    path('homepage/', views.homepage, name='homepage'),
    path('Add/', views.Add, name='Add'),
    path('largest/', views.largest, name='largest'),
    path('calculator/', views.calculator, name='calculator'),
    path('register/', views.register, name='register'),
    path('district/', views.district, name='district'),
    path('category/', views.category, name='category'),
    path('delcategory/<int:id>', views.delcategory, name='delcategory'),
    path('editcategory/<int:id>', views.editcategory, name='editcategory'),
    path('deldistrict/<int:id>', views.deldistrict, name='deldistrict'),
    path('editdistrict/<int:id>', views.editdistrict, name='editdistrict'),
    path('adminregister/', views.adminregister, name='adminregister'),
    path('deladminreg/<int:id>', views.deladminreg, name='deladminreg'),
    path('editadminreg/<int:id>', views.editadminreg, name='editadminreg'),
    path('place/', views.place, name='place'),
    path('delplace/<int:id>', views.delplace, name='delplace'),
    path('editplace/<int:id>', views.editplace, name='editplace'),
    path('subcategory/', views.subcategory, name='subcategory'),
    path('delsubcategory/<int:id>', views.delsub, name='delsubcategory'),
    path('editsubcategory/<int:id>', views.editsub, name='editsubcategory'),
    path('verification/', views.verification, name='verification'),
    # path('useraccept/<int:id>', views.useraccept, name='useraccept'),
    path('userreject/<int:id>', views.userreject, name='userreject'),
    # path('product/', views.product, name='product'),
    path('ajaxsub/', views.ajaxsub, name='ajaxsub'),
    path('newdesigner/', views.newdesigner, name='newdesigner'),
    path('designeraccept/<int:id>', views.designeraccept, name='designeraccept'),
    path('designerreject/<int:id>', views.designerreject, name='designerreject'),
    path('accepteddesigner/', views.accepteddesigner, name='accepteddesigner'),
    path('rejecteddesigner/', views.rejecteddesigner, name='rejecteddesigner'),
    path('adminhome/',views.adminhome,name="adminhome"),
    path('newshops/', views.newshops, name='newshops'),
    path('shopaccept/<int:id>', views.shopaccept, name='shopaccept'),
    path('shopreject/<int:id>', views.shopreject, name='shopreject'),
    path('acceptedshops', views.acceptedshops, name='acceptedshops'),
     path('rejectedshop', views.rejectedshops, name='rejectedshop'),
      path('feedback', views.viewfeeback, name='feedback'),
      path('viewcomplaints/', views.viewcomplaints, name='viewcomplaints'),
    path('replay/<int:id>',views.replay,name='replay'),
    path('replayedcomplaint/',views.replayedcomplaint,name='replayedcomplaint'),
     path('logout/',views.logout,name='logout'),
    ]
    

