# Generated by Django 5.1.3 on 2024-12-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='User_status',
            field=models.IntegerField(default=0),
        ),
    ]
