# Generated by Django 5.1.3 on 2024-12-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_user_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='User_status',
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='user_status',
            field=models.IntegerField(default=0),
        ),
    ]
