# Generated by Django 5.1.3 on 2024-12-17 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_product'),
        ('Guest', '0003_remove_tbl_user_user_status_tbl_user_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name', models.CharField(max_length=30)),
                ('designer_email', models.CharField(max_length=30)),
                ('designer_contact', models.CharField(max_length=30)),
                ('designer_address', models.CharField(max_length=50)),
                ('designer_photo', models.FileField(upload_to='Assets/User/Photo/')),
                ('designer_proof', models.FileField(upload_to='Assets/User/Photo/')),
                ('designer_password', models.CharField(max_length=30)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
