# Generated by Django 5.1.3 on 2024-12-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_designer',
            name='designer_status',
            field=models.IntegerField(default=0),
        ),
    ]
