# Generated by Django 5.1.3 on 2024-12-18 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_product'),
        ('Guest', '0005_tbl_designer_designer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=30)),
                ('shop_email', models.CharField(max_length=30)),
                ('shop_contact', models.CharField(max_length=30)),
                ('shop_address', models.CharField(max_length=30)),
                ('shop_photo', models.FileField(upload_to='Assets/User/Photo/')),
                ('shop_proof', models.FileField(upload_to='Assets/User/Photo/')),
                ('shop_password', models.CharField(max_length=30)),
                ('shop_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
