# Generated by Django 5.1.3 on 2024-12-20 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Designer', '0008_delete_tbl_designrequest'),
        ('Guest', '0006_tbl_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_designrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designrequest_date', models.CharField(max_length=30)),
                ('designrequest_todate', models.CharField(max_length=30)),
                ('designrequest_status', models.IntegerField(default=0)),
                ('designrequest_amount', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Designer.tbl_work')),
            ],
        ),
    ]
