# Generated by Django 5.1.3 on 2024-12-20 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_shop'),
        ('User', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=30)),
                ('complaint_description', models.CharField(max_length=30)),
                ('complaint_date', models.CharField(max_length=30)),
                ('complaint_status', models.CharField(max_length=30)),
                ('complaint_replay', models.CharField(max_length=30)),
                ('desginer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_designer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
