# Generated by Django 5.1.3 on 2024-12-21 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_tbl_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
