# Generated by Django 5.1.3 on 2024-12-21 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_shop'),
        ('User', '0011_tbl_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='desginer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_designer'),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop'),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
    ]
