# Generated by Django 5.1.3 on 2024-12-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_alter_tbl_complaint_desginer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_status',
            field=models.IntegerField(default=0),
        ),
    ]
