# Generated by Django 5.1.3 on 2024-12-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_tbl_booking_tbl_cart_tbl_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cart',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='product',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_cart',
        ),
    ]
