# Generated by Django 5.1.3 on 2024-12-28 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_shop'),
        ('User', '0016_tbl_booking_tbl_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('shop_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_from', to='Guest.tbl_shop')),
                ('shop_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_to', to='Guest.tbl_shop')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Guest.tbl_user')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Guest.tbl_user')),
            ],
        ),
    ]
