# Generated by Django 5.1.7 on 2025-04-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
